# Generated by Django 5.2.11 on 2026-08-02 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_login_links_no_passwords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passkey',
            name='is_discoverable',
        ),
        migrations.RemoveField(
            model_name='passkey',
            name='transports',
        ),
    ]
