# Generated by Django 5.2.11 on 2026-07-29 22:17

import apps.core.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0003_role_drop_trust_and_personal_info_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('completion', 'Requirement marked complete'), ('document', 'Document recorded'), ('crc', 'Criminal record check'), ('waiver', 'Requirement waived'), ('override', 'Leadership override')], db_index=True, max_length=32)),
                ('entity_type', models.CharField(db_index=True, max_length=64)),
                ('entity_id', models.CharField(db_index=True, max_length=64)),
                ('entity_label', models.CharField(blank=True, max_length=200)),
                ('affected_entity_type', models.CharField(blank=True, db_index=True, max_length=64)),
                ('affected_entity_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Awaiting review'), ('affirmed', 'Affirmed'), ('sent_back', 'Sent back'), ('superseded', 'Superseded before review')], db_index=True, default='pending', max_length=16)),
                ('recorded_by_user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('recorded_by_display', models.CharField(default='', max_length=150)),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reviewed_by_user_id', models.IntegerField(blank=True, null=True)),
                ('reviewed_by_display', models.CharField(blank=True, max_length=150)),
                ('decision_reason', apps.core.fields.EncryptedTextField(blank=True, default='')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_items', to='org.department')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='review.reviewitem')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_items', to='org.volunteer')),
            ],
            options={
                'verbose_name': 'review item',
                'verbose_name_plural': 'review queue',
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['status', 'created_at'], name='review_revi_status_a3a3d3_idx'), models.Index(fields=['status', 'entity_type', 'entity_id'], name='review_revi_status_8f1f78_idx'), models.Index(fields=['status', 'affected_entity_type', 'affected_entity_id'], name='review_revi_status_ab3748_idx'), models.Index(fields=['volunteer', 'status'], name='review_revi_volunte_aa79e1_idx'), models.Index(fields=['recorded_by_user_id', 'status'], name='review_revi_recorde_d53693_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('entity_type', 'entity_id'), name='one_open_review_per_entity'), models.CheckConstraint(condition=models.Q(('status', 'pending'), ('reviewed_at__isnull', False), _connector='OR'), name='closed_review_has_a_timestamp')],
            },
        ),
    ]
