# Generated by Django 5.2.11 on 2026-07-25 02:34

import apps.core.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('actor_user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('actor_display', models.CharField(default='system', max_length=150)),
                ('actor_ip', models.CharField(blank=True, max_length=45)),
                ('actor_user_agent', models.CharField(blank=True, max_length=200)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('deactivate', 'Deactivated'), ('reactivate', 'Reactivated'), ('status_change', 'Status changed'), ('waive', 'Waived'), ('upload', 'Document uploaded'), ('download', 'Document viewed'), ('login', 'Signed in'), ('login_failed', 'Sign-in failed'), ('logout', 'Signed out'), ('crc_recorded', 'Criminal record check recorded'), ('disqualified', 'Permanently disqualified'), ('override', 'Leadership override recorded'), ('key_backup', 'Encryption key backed up'), ('notify', 'Notification sent'), ('seed', 'Template seeded')], db_index=True, max_length=32)),
                ('entity_type', models.CharField(db_index=True, max_length=64)),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('entity_label', models.CharField(blank=True, max_length=200)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('detail', apps.core.fields.EncryptedTextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'audit event',
                'verbose_name_plural': 'audit trail',
                'ordering': ('-occurred_at', '-id'),
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='core_audite_entity__e1955d_idx'), models.Index(fields=['-occurred_at', 'action'], name='core_audite_occurre_5ce164_idx')],
            },
        ),
    ]
