# Generated by Django 5.2.11 on 2026-07-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_backfill_primary_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('deactivate', 'Deactivated'), ('reactivate', 'Reactivated'), ('status_change', 'Status changed'), ('waive', 'Waived'), ('waiver_reversed', 'Waiver reversed'), ('upload', 'Document uploaded'), ('download', 'Document viewed'), ('login', 'Signed in'), ('login_failed', 'Sign-in failed'), ('logout', 'Signed out'), ('link_issued', 'Sign-in link issued'), ('link_used', 'Sign-in link used'), ('crc_recorded', 'Criminal record check recorded'), ('disqualified', 'Permanently disqualified'), ('override', 'Leadership override recorded'), ('key_backup', 'Encryption key backed up'), ('notify', 'Notification sent'), ('seed', 'Template seeded'), ('access_changed', 'Access level changed')], db_index=True, max_length=32),
        ),
    ]
