# Generated by Django 5.2.11 on 2026-07-25 02:34

import apps.core.fields
import apps.documents.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('crc', 'Criminal record check clearance'), ('application', 'Application form'), ('reference', 'Reference check'), ('agreement', 'Signed agreement'), ('training', 'Training certificate'), ('interview', 'Interview record'), ('approval', 'Leadership approval'), ('other', 'Other')], default='other', max_length=16)),
                ('mode', models.CharField(db_index=True, max_length=8)),
                ('title', models.CharField(help_text="A short label, e.g. 'CRC clearance letter 2026'. Avoid personal details.", max_length=200)),
                ('document_date', models.DateField(blank=True, help_text='The date on the document itself.', null=True)),
                ('encrypted_file', models.FileField(blank=True, max_length=255, null=True, upload_to=apps.documents.models.encrypted_upload_path)),
                ('original_filename', apps.core.fields.EncryptedCharField(blank=True, default='', help_text='Encrypted.', max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('byte_size', models.PositiveIntegerField(blank=True, null=True)),
                ('plaintext_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('external_url', models.URLField(blank=True, help_text="Where this document lives in the church's own document store.", max_length=500)),
                ('physical_location', models.CharField(blank=True, help_text="Where the hard copy is filed, e.g. 'Office cabinet 2, folder B'.", max_length=200)),
                ('notes', apps.core.fields.EncryptedTextField(blank=True, default='', help_text='Encrypted.')),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=150)),
                ('crc_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='requirements.crcrecord')),
                ('requirement_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='requirements.requirementinstance')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='documents.document')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='org.volunteer')),
            ],
            options={
                'ordering': ('-document_date', '-created_at'),
                'indexes': [models.Index(fields=['volunteer', 'kind'], name='documents_d_volunte_6bd141_idx'), models.Index(fields=['kind', 'is_current'], name='documents_d_kind_9fd4e7_idx')],
            },
        ),
    ]
