# Generated by Django 5.2.11 on 2026-07-25 02:34

import apps.tenants.models
import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(help_text="The church's full legal or common name.", max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('document_mode', models.CharField(choices=[('store', 'Store securely in-system (encrypted)'), ('link', 'Track status and link to our own external store'), ('track', 'Track status and dates only (hard copy retained)')], default='store', help_text='Changeable later by the platform super-admin.', max_length=8)),
                ('dek_wrapped', models.BinaryField(default=b'')),
                ('dek_fingerprint', models.CharField(blank=True, editable=False, help_text='Non-reversible key identifier, for confirming a restored key matches.', max_length=32)),
                ('key_backup_confirmed_at', models.DateTimeField(blank=True, help_text="Set when the church's admin confirmed they saved the key offline.", null=True)),
                ('key_backup_confirmed_by', models.CharField(blank=True, max_length=150)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('reminder_lead_days', models.CharField(default='60,30,7', help_text="Days before expiry to email the church's admins, comma separated.", max_length=64, validators=[apps.tenants.models.validate_lead_days])),
                ('is_active', models.BooleanField(default=True, help_text='Inactive churches keep their data but are refused at the door.')),
                ('notes', models.TextField(blank=True, help_text='Operator notes. Not visible to the church.')),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'church',
                'verbose_name_plural': 'churches',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'ordering': ('domain',),
            },
        ),
    ]
