# Generated by Django 5.2.11 on 2026-07-25 02:34

import apps.core.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRCRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(choices=[('cleared', 'Cleared'), ('not_clear', 'Not Clear')], db_index=True, max_length=16)),
                ('report_date', models.DateField(db_index=True, help_text='The date on the clearance letter. This starts the three-year clock.')),
                ('includes_vulnerable_sector', models.BooleanField(default=True, help_text='A vulnerable sector search is required for positions of trust.')),
                ('is_fingerprint_verified', models.BooleanField(default=False, help_text="Set for a fingerprint-verified check following a 'Not Clear' result.")),
                ('not_clear_outcome', models.CharField(blank=True, choices=[('pending', "Awaiting the volunteer's decision"), ('fingerprint', 'Fingerprint-verified check submitted'), ('withdrew', 'Volunteer withdrew')], default='', help_text="How a 'Not Clear' result was resolved.", max_length=16)),
                ('issuing_body', models.CharField(blank=True, help_text="e.g. 'BC Criminal Record Review Program' or the local police service.", max_length=150)),
                ('notes', apps.core.fields.EncryptedTextField(blank=True, default='', help_text='Encrypted.')),
                ('superseded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='requirements.crcrecord')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crc_records', to='org.volunteer')),
            ],
            options={
                'verbose_name': 'criminal record check',
                'ordering': ('-report_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DisqualifyingConviction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(help_text='The policy category this conviction falls under.', max_length=100)),
                ('is_automatic_disqualifier', models.BooleanField(help_text='Automatic disqualifiers permanently bar this person from all positions of trust. This cannot be overridden.')),
                ('description', apps.core.fields.EncryptedTextField(blank=True, default='', help_text='Details as disclosed and verified. Encrypted.')),
                ('conviction_date', models.DateField(blank=True, null=True)),
                ('recorded_by', models.CharField(blank=True, max_length=150)),
                ('crc_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convictions', to='requirements.crcrecord')),
            ],
            options={
                'verbose_name': 'conviction',
                'ordering': ('-is_automatic_disqualifier', 'category'),
            },
        ),
        migrations.CreateModel(
            name='DiscretionaryOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('approved', 'Approved to serve'), ('conditional', 'Approved with conditions'), ('declined', 'Declined')], max_length=16)),
                ('decided_on', models.DateField(default=django.utils.timezone.localdate)),
                ('decided_by', models.CharField(help_text='The leader or leadership body making this decision.', max_length=150)),
                ('reasoning', apps.core.fields.EncryptedTextField(help_text='Why this decision was reached. Required.')),
                ('mitigation_steps', apps.core.fields.EncryptedTextField(help_text='What safeguards are in place as a result. Required.')),
                ('crc_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overrides', to='requirements.crcrecord')),
                ('conviction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overrides', to='requirements.disqualifyingconviction')),
            ],
            options={
                'verbose_name': 'leadership override',
                'ordering': ('-decided_on',),
            },
        ),
        migrations.CreateModel(
            name='RequirementDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='What this requires and how an admin should verify it.')),
                ('appendix_reference', models.CharField(blank=True, help_text="Where to find the form in your policy manual, e.g. 'Appendix 2d'. A pointer only — no policy text is stored in this system.", max_length=100)),
                ('requirement_type', models.CharField(choices=[('application_form', 'Application form'), ('waiting_period', 'Waiting period'), ('declaration_of_faith', 'Statement / declaration of faith'), ('liability_release', 'Liability release'), ('reference_checks', 'Reference checks'), ('interview', 'Interview'), ('policy_agreement', 'Plan to Protect policy agreement'), ('criminal_record_check', 'Criminal record check'), ('training_orientation', 'Orientation training'), ('training_refresher', 'Refresher training'), ('signed_agreement', 'Signed agreement'), ('leadership_approval', 'Leadership approval'), ('custom', 'Custom requirement')], db_index=True, max_length=32)),
                ('cadence', models.CharField(choices=[('one_time', 'One time only'), ('annual', 'Annually'), ('every_3_years', 'Every 3 years'), ('custom_months', 'Every N months')], default='one_time', max_length=16)),
                ('cadence_months', models.PositiveSmallIntegerField(blank=True, help_text="Only used when the cadence is 'Every N months'.", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)])),
                ('applies_to', models.CharField(choices=[('all', 'Everyone'), ('specific', 'Only the selected roles'), ('leadership', 'Roles flagged as leadership'), ('personal_info', 'Roles that handle personal information'), ('trust', 'Positions of trust')], default='all', max_length=16)),
                ('age_rule', models.CharField(choices=[('none', 'Applies at any age'), ('adults_only', 'Adults only (18+)')], default='none', max_length=16)),
                ('sequence', models.PositiveSmallIntegerField(default=100, help_text='Lower numbers come first in the onboarding checklist.')),
                ('is_onboarding', models.BooleanField(default=True, help_text='Part of the one-time onboarding sequence, rather than a recurring item.')),
                ('requires_document', models.BooleanField(default=False, help_text='Expect a document (or a link, or a paper record) to evidence this.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_seeded', models.BooleanField(default=False, editable=False, help_text='Came from the Plan to Protect starter template. Editable like any other.')),
                ('must_follow', models.ForeignKey(blank=True, help_text='Optional ordering rule. The policy requires the liability release to be signed before reference checks are sought, for example.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followed_by', to='requirements.requirementdefinition')),
                ('roles', models.ManyToManyField(blank=True, help_text="Used only when 'Only the selected roles' is chosen.", related_name='requirement_definitions', to='org.role')),
            ],
            options={
                'ordering': ('sequence', 'name'),
            },
        ),
        migrations.CreateModel(
            name='RequirementInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('complete', 'Complete'), ('overdue', 'Overdue'), ('not_applicable', 'Not applicable'), ('waived', 'Waived'), ('blocked', 'Blocked')], db_index=True, default='not_started', max_length=16)),
                ('started_on', models.DateField(blank=True, help_text='When work on this began. Used to warn if onboarding exceeds 3 months.', null=True)),
                ('completed_on', models.DateField(blank=True, db_index=True, null=True)),
                ('expires_on', models.DateField(blank=True, db_index=True, help_text='Computed from the completion date and the cadence.', null=True)),
                ('due_on', models.DateField(blank=True, db_index=True, help_text='A hard deadline independent of the renewal cycle.', null=True)),
                ('due_reason', models.CharField(blank=True, max_length=200)),
                ('waived_reason', apps.core.fields.EncryptedTextField(blank=True, default='', help_text='Required when waiving. Recorded in the audit trail.')),
                ('waived_by', models.CharField(blank=True, max_length=150)),
                ('waived_on', models.DateField(blank=True, null=True)),
                ('not_applicable_reason', models.CharField(blank=True, help_text="Plain, non-identifying reason, e.g. 'Under 18 — no CRC required'.", max_length=200)),
                ('notes', apps.core.fields.EncryptedTextField(blank=True, default='', help_text='Encrypted.')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='requirements.requirementdefinition')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirement_instances', to='org.volunteer')),
            ],
            options={
                'ordering': ('definition__sequence', 'definition__name'),
            },
        ),
        migrations.AddField(
            model_name='crcrecord',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crc_records', to='requirements.requirementinstance'),
        ),
        migrations.AddIndex(
            model_name='requirementdefinition',
            index=models.Index(fields=['is_active', 'requirement_type'], name='requirement_is_acti_d69e39_idx'),
        ),
        migrations.AddConstraint(
            model_name='requirementdefinition',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_requirement_name'),
        ),
        migrations.AddConstraint(
            model_name='requirementdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('cadence_months__isnull', False), models.Q(('cadence', 'custom_months'), _negated=True), _connector='OR'), name='custom_cadence_needs_months'),
        ),
        migrations.AddIndex(
            model_name='requirementinstance',
            index=models.Index(fields=['status', 'expires_on'], name='requirement_status_36b478_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementinstance',
            index=models.Index(fields=['volunteer', 'status'], name='requirement_volunte_842dc6_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementinstance',
            index=models.Index(fields=['expires_on'], name='requirement_expires_cc4bce_idx'),
        ),
        migrations.AddConstraint(
            model_name='requirementinstance',
            constraint=models.UniqueConstraint(fields=('volunteer', 'definition'), name='unique_instance_per_volunteer'),
        ),
        migrations.AddIndex(
            model_name='crcrecord',
            index=models.Index(fields=['volunteer', '-report_date'], name='requirement_volunte_424d39_idx'),
        ),
        migrations.AddIndex(
            model_name='crcrecord',
            index=models.Index(fields=['result', 'report_date'], name='requirement_result_96e893_idx'),
        ),
    ]
