# Generated by Django 5.2.11 on 2026-07-29 01:38

import django.core.validators
import django.db.models.deletion
"""
Give ``must_follow`` a rule, so a dependency can gate as well as warn.

Deliberately inert on upgrade. ``dependency_mode`` defaults to ``warn``, which is
exactly what every existing dependency already does, so the one seeded pair
(reference checks after the liability release) keeps behaving as it did. Gating is
opted into per requirement.
"""

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0002_retarget_universal_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementdefinition',
            name='dependency_mode',
            field=models.CharField(choices=[('warn', 'Warn if completed out of order'), ('gate', 'Does not apply until the prerequisite is complete')], default='warn', help_text='Warn: an admin recording paperwork out of order is told, but not stopped. Gate: this does not apply at all until the other is complete, and its deadline is counted from that completion.', max_length=8, verbose_name='dependency rule'),
        ),
        migrations.AddField(
            model_name='requirementdefinition',
            name='due_months_after_prerequisite',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Gate only. Leave blank to use this requirement's own cadence — an annual refresher then falls due a year after the training it follows.", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)], verbose_name='months after the prerequisite'),
        ),
        migrations.AlterField(
            model_name='requirementdefinition',
            name='must_follow',
            field=models.ForeignKey(blank=True, help_text='Optional. Another requirement this one follows — the policy requires the liability release before references are sought, for example. What that means in practice is set by the dependency rule below.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followed_by', to='requirements.requirementdefinition', verbose_name='depends on'),
        ),
    ]
