# Generated by Django 5.2.11 on 2026-07-25 02:34

import apps.core.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, help_text='What this department does. Plain text; visible to all admins.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive departments are hidden from pickers but keep their history.')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, help_text='Plain-text description of the position and its responsibilities.')),
                ('leadership', models.CharField(choices=[('none', 'Not a leadership role'), ('director', 'Director'), ('secretary', 'Secretary')], db_index=True, default='none', help_text='Directors and secretaries are screened exactly like any other volunteer; this only records that the position is a leadership one.', max_length=16)),
                ('handles_personal_info', models.BooleanField(db_index=True, default=False, help_text='Tick for roles with access to personal information. Requirements such as the Confidentiality Agreement target this flag.')),
                ('is_position_of_trust', models.BooleanField(default=True, help_text='Positions of trust require full screening. Untick only for roles with no access to children, youth or vulnerable adults.')),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(help_text='A role belongs to exactly one department.', on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='org.department')),
            ],
            options={
                'ordering': ('department__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('preferred_name', models.CharField(blank=True, help_text='Optional. Used in lists where set.', max_length=100)),
                ('birth_year', models.PositiveIntegerField(blank=True, db_index=True, help_text='Required to apply the under-18 and turning-18 rules.', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('birth_month', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('date_of_birth', apps.core.fields.EncryptedDateField(blank=True, help_text='Encrypted. The year and month are stored separately to drive age rules.', null=True, verbose_name='full date of birth')),
                ('email', apps.core.fields.EncryptedEmailField(blank=True, default='', help_text='Encrypted.', max_length=254)),
                ('phone', apps.core.fields.EncryptedCharField(blank=True, default='', help_text='Encrypted.', max_length=40)),
                ('address', apps.core.fields.EncryptedTextField(blank=True, default='', help_text='Encrypted.', verbose_name='home address')),
                ('emergency_contact', apps.core.fields.EncryptedTextField(blank=True, default='', help_text='Name, relationship and phone number. Encrypted.')),
                ('medical_notes', apps.core.fields.EncryptedTextField(blank=True, default='', help_text='Encrypted. Record only what is needed to keep this person safe.', verbose_name='medical / allergy details')),
                ('notes', apps.core.fields.EncryptedTextField(blank=True, default='', help_text='Encrypted admin notes.')),
                ('attendance_since', models.DateField(blank=True, help_text='When regular attendance began. Drives the six-month waiting period; leave blank for a transfer with references from a previous minister.', null=True)),
                ('is_transfer', models.BooleanField(default=False, help_text='Transferring from another church. The waiting period may be waived given three references including the previous minister.')),
                ('screening_block', models.CharField(choices=[('none', 'Not blocked'), ('crc_not_clear', 'Blocked — criminal record check not clear'), ('disqualified', 'Permanently disqualified'), ('withdrawn', 'Withdrew from screening')], db_index=True, default='none', editable=False, help_text='Maintained by the criminal-record-check flow; not directly editable.', max_length=16)),
                ('screening_block_recorded_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Untick when someone stops serving. The file is always retained.')),
                ('stopped_serving_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='org_volunte_last_na_afc3b7_idx'), models.Index(fields=['birth_year', 'birth_month'], name='org_volunte_birth_y_929862_idx'), models.Index(fields=['is_active', 'screening_block'], name='org_volunte_is_acti_86dac0_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_on', models.DateField(default=django.utils.timezone.localdate)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='org.role')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='org.volunteer')),
            ],
            options={
                'ordering': ('-is_active', '-started_on'),
            },
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('department', 'name'), name='unique_role_name_per_department'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['role', 'is_active'], name='org_roleass_role_id_84cde0_idx'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('volunteer', 'role'), name='unique_active_assignment'),
        ),
    ]
