# Generated by Django 5.2.11 on 2026-08-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_role_drop_trust_and_personal_info_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='user_id',
            field=models.IntegerField(blank=True, db_index=True, editable=False, help_text='Set when this volunteer is also a screening administrator. Nobody may record screening against their own file while somebody else could.', null=True, unique=True, verbose_name='linked administrator'),
        ),
    ]
