# Generated by Django 5.2.11 on 2026-07-25 02:34

import apps.core.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=8)),
                ('recipients', apps.core.fields.EncryptedTextField(default='', help_text='Comma-separated. Encrypted.')),
                ('subject', apps.core.fields.EncryptedTextField(default='', help_text='Encrypted.')),
                ('body', apps.core.fields.EncryptedTextField(default='', help_text='Encrypted.')),
                ('recipient_count', models.PositiveSmallIntegerField(default=0)),
                ('item_count', models.PositiveSmallIntegerField(default=0, help_text='How many requirements this digest covered.')),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('error', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'email log entry',
                'verbose_name_plural': 'email log',
                'ordering': ('-sent_at',),
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('lead_time', 'Approaching expiry'), ('overdue', 'Overdue'), ('turning_18', 'Criminal record check due on turning 18')], max_length=16)),
                ('lead_days', models.PositiveSmallIntegerField(default=0)),
                ('expiry_at_send', models.DateField(blank=True, null=True)),
                ('raised_on', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='requirements.requirementinstance')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['raised_on', 'kind'], name='notificatio_raised__6d5de0_idx')],
                'constraints': [models.UniqueConstraint(fields=('instance', 'kind', 'lead_days', 'expiry_at_send'), name='unique_reminder_per_cycle')],
            },
        ),
    ]
